### ISSUE TITLE
Decide on and add OpenArena shortened game types names

### ISSUE THREAD

**Issue by torhus** [torhus/monster-browser#15]
Here are suggestions for abbreviated names for displaying in Monster Browser, trying to make them easily recognizable for OA players. Does this look ok?

 n  | Full Name                | Shortened 
----|--------------------------|-----------
 0  | Free For All             | FFA       
 1  | Tournament               | 1v1       
 2  | Single Player Deathmatch | SP        
 3  | Team Deathmatch          | TDM       
 4  | Capture the Flag         | CTF       
 5  | One Flag Capture         | OFC       
 6  | Overload                 | Ovl       
 7  | Harvester                | Harv      
 8  | Elimination              | Elim      
 9  | CTF Elimination          | CTFE      
 10 | Last Man Standing        | LMS       
 11 | Double Domination        | DD        
 12 | Domination               | Dom       
 13 | Possession               | Poss      

Game config line:
`gameTypes=FFA 1v1 SP TDM CTF OFC Ovl Harv Elim CTFE LMS DD Dom Poss`

I see some servers running "rat" are using game type 14, should I add a name for that?

**Comment by The-Gig** [comment]
Hi, I'm back from vacation. Let's see, they sound ok for me. I'm a bit unsure about maybe just using "Pos" for "Possession", simply due to the fact that in the gametype key mappers can use to use show or not entities in a certain gametype, it's "pos" (https://openarena.fandom.com/wiki/Mapping_manual/Additional_gametype_support?so=search#The_%22gametype%22_and_%22!gametype%22_keys), but anyway I don't think it's a problem, since also for others gametypes we can see their names shortened in different ways...

About "rat", that's the name of a mod, so in case baseoa will ever have a gametype 14, I don't think it will be "rat".
